# Setup
title:          "Studio W Plecaku.pl"
description:    "Archiwum bloga Studio W Plecaku.pl"
url:            "https://studiowplecaku.pl"
future:         true
permalink:      pretty

# Pagination
paginate:       15

# Sass converter configuration
sass:
  style:        compressed

# Local Server
host:           localhost # same as default value '127.0.0.1' but reads better

# Links
main:           "https://studiowplecaku.pl"

# Social
authors:        "Jarek Sikora"

logo:           "/assets/img/bootstrap-social.png"

# Output
defaults:
  - scope:
      path:     ""
    values:
      image:
        path:   "/assets/img/bootstrap-social.png" # default image
        width:  1200
        height: 630

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap

exclude:
  - .sass-cache
  - .netlify
  - vendor/
  - Gemfile
  - Gemfile.lock
  - README.md
